name: gnn-brainnets
channels:
  - defaults
dependencies:
  - anyio=4.2.0=py38hecd8cb5_0
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38hca72f7f_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38hecd8cb5_0
  - attrs=23.1.0=py38hecd8cb5_0
  - babel=2.11.0=py38hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38hecd8cb5_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py38hcec6c5f_8
  - ca-certificates=2024.7.2=hecd8cb5_0
  - certifi=2024.7.4=py38hecd8cb5_0
  - cffi=1.16.0=py38h6c40b1e_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py38hecd8cb5_0
  - debugpy=1.6.7=py38hcec6c5f_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py38hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib-metadata=7.0.1=py38hecd8cb5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38hecd8cb5_0
  - ipykernel=6.28.0=py38hecd8cb5_0
  - ipython=8.12.2=py38hecd8cb5_0
  - jedi=0.19.1=py38hecd8cb5_0
  - jinja2=3.1.4=py38hecd8cb5_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py38hecd8cb5_0
  - jsonschema-specifications=2023.7.1=py38hecd8cb5_0
  - jupyter-lsp=2.2.0=py38hecd8cb5_0
  - jupyter_client=8.6.0=py38hecd8cb5_0
  - jupyter_core=5.7.2=py38hecd8cb5_0
  - jupyter_events=0.10.0=py38hecd8cb5_0
  - jupyter_server=2.14.1=py38hecd8cb5_0
  - jupyter_server_terminals=0.4.4=py38hecd8cb5_1
  - jupyterlab=4.0.11=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py38hecd8cb5_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.18=h1de35cc_0
  - matplotlib-inline=0.1.6=py38hecd8cb5_0
  - mistune=2.0.4=py38hecd8cb5_0
  - nbclient=0.8.0=py38hecd8cb5_0
  - nbconvert=7.10.0=py38hecd8cb5_0
  - nbformat=5.9.2=py38hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=py38hecd8cb5_0
  - notebook-shim=0.2.3=py38hecd8cb5_0
  - openssl=3.0.14=h46256e1_0
  - overrides=7.4.0=py38hecd8cb5_0
  - packaging=24.1=py38hecd8cb5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38hecd8cb5_0
  - pkgutil-resolve-name=1.3.10=py38hecd8cb5_1
  - platformdirs=3.10.0=py38hecd8cb5_0
  - prometheus_client=0.14.1=py38hecd8cb5_0
  - prompt-toolkit=3.0.43=py38hecd8cb5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38hecd8cb5_1
  - pysocks=1.7.1=py38_1
  - python=3.8.19=h5ee71fb_0
  - python-dateutil=2.9.0post0=py38hecd8cb5_2
  - python-fastjsonschema=2.16.2=py38hecd8cb5_0
  - python-json-logger=2.0.7=py38hecd8cb5_0
  - pytz=2024.1=py38hecd8cb5_0
  - pyyaml=6.0.1=py38h6c40b1e_0
  - pyzmq=25.1.2=py38hcec6c5f_0
  - readline=8.2=hca72f7f_0
  - referencing=0.30.2=py38hecd8cb5_0
  - requests=2.32.3=py38hecd8cb5_0
  - rfc3339-validator=0.1.4=py38hecd8cb5_0
  - rfc3986-validator=0.1.1=py38hecd8cb5_0
  - rpds-py=0.10.6=py38hf2ad997_0
  - send2trash=1.8.2=py38hecd8cb5_0
  - setuptools=72.1.0=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38hecd8cb5_0
  - soupsieve=2.5=py38hecd8cb5_0
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38hecd8cb5_0
  - tinycss2=1.2.1=py38hecd8cb5_0
  - tk=8.6.14=h4d00af3_0
  - tomli=2.0.1=py38hecd8cb5_0
  - tornado=6.4.1=py38h46256e1_0
  - traitlets=5.14.3=py38hecd8cb5_0
  - typing_extensions=4.11.0=py38hecd8cb5_0
  - urllib3=2.2.2=py38hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38hecd8cb5_0
  - wheel=0.43.0=py38hecd8cb5_0
  - xz=5.4.6=h6c40b1e_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.5=hcec6c5f_0
  - zipp=3.17.0=py38hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - pip:
      - alembic==1.13.3
      - click==8.1.7
      - colorlog==6.8.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.11
      - decorator==4.4.2
      - deepchem==2.7.1
      - docker-pycreds==0.4.0
      - et-xmlfile==2.0.0
      - fasttext==0.9.3
      - fonttools==4.53.1
      - fst-pso==1.8.1
      - fuzzytm==2.0.9
      - gensim==4.3.0
      - giotto-ph==0.2.4
      - giotto-tda==0.6.2
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.1.1
      - idna==3.8
      - igraph==0.11.8
      - ipywidgets==8.1.5
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - mako==1.3.5
      - markupsafe==2.1.5
      - matplotlib==3.6.3
      - miniful==0.0.6
      - narwhals==1.38.2
      - networkx==2.8.8
      - node2vec==0.4.6
      - numpy==1.24.4
      - openpyxl==3.1.5
      - optuna==4.0.0
      - pandas==1.5.2
      - patsy==0.5.6
      - pillow==10.4.0
      - plotly==6.0.1
      - protobuf==5.28.2
      - psutil==6.0.0
      - pybind11==2.13.6
      - pyflagser==0.4.7
      - pyfume==0.3.4
      - pyparsing==3.1.4
      - rdkit==2024.3.5
      - scikit-learn==1.3.2
      - scipy==1.8.1
      - seaborn==0.12.2
      - sentry-sdk==2.15.0
      - setproctitle==1.3.3
      - simpful==2.12.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sqlalchemy==2.0.35
      - statsmodels==0.14.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - torch==1.13.1
      - torch-cluster==1.6.0
      - torch-geometric==2.2.0
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.1.0
      - torch-sparse==0.6.16
      - torch-spline-conv==1.2.1
      - torchaudio==0.13.1
      - torchsummary==1.5.1
      - torchvision==0.14.1
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - wandb==0.18.3
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
